spring.application.name=task-track
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=Minhavida222
spring.jpa.hibernate.ddl-auto=update